##### Menu
menu:
  博客: /
  归档: /archives
  关于我: /about
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as1
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets  
widgets: 
## - github-card
- category
- tag
- links
- douban
- rss
- weibo
  ## provide eight widgets:github-card,category,tag,rss,archive,tagcloud,links,weibo

#### RSS 
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.     
apple_icon: img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
banner_img: #img/banner.jpg ## size:1920px*200px+. Banner Picture
### Theme Color 
theme_color:
    theme: '#148EEB'    ##the defaut theme color is blue

# 代码高亮主题
# available: default | night
highlight_theme: default

#### index post is expanding or not 
index:
  expand: false           ## default is unexpanding,so you can only see the short description of each post. 首页文章展开，这个展开的话，很丑
  excerpt_link: Read More  

### Creative Commons License Support, see http://creativecommons.org/ 
### you can choose: by , by-nc , by-nc-nd , by-nc-sa , by-nd , by-sa , zero
creative_commons: none

#### Author information
author:
  intro_line1: "Hi,I'm Liu Jing,It's my blog,web home." ## eg: "Hello ,I'm Larry Page in Google."
  intro_line2: "I'd would like to share with you at this blog." ## eg: "This is my blog,believe it or not."
  weibo: cnliujing     ## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895
  weibo_verifier: 660d5795    ## e.g. b3593ceb Your weibo-show widget verifier ,if you use weibo-show it is needed. 微博秀的验证码
  tsina: 5718691796     ## e.g. 2176287895  Your weibo ID,It will be used in share button.,uid=5718691796,不知道用哪个现在
  douban:     ## e.g. 1wuchong1014 or your id for https://www.douban.com/people/wuchong1014   shliujing，先不放，放了就歪了。应该是BUG  
  zhihu: shliujing     ## e.g. jark  for http://www.zhihu.com/people/jark
  email: wkliujing@foxmail.com     ## e.g. imjark@gmail.com
  twitter: shliujing   ## e.g. jarkwu for https://twitter.com/jarkwu
  github: shliujing    ## e.g. wuchong for https://github.com/wuchong
  facebook: shliujing  ## e.g. imjark for https://facebook.com/imjark
  linkedin: shliujing  ## e.g. wuchong1014 for https://www.linkedin.com/in/wuchong1014
  google_plus:    ## e.g. "111190881341800841449" for https://plus.google.com/u/0/111190881341800841449, the "" is needed!
  stackoverflow: shliujing ## e.g. 3222790 for http://stackoverflow.com/users/3222790/jark
## if you set them, the corresponding  share button will show on the footer

#### Toc
toc:
  article: false   ## show contents in article.
  article: false   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  知乎: https://zhihu.com

#### Comment
duoshuo_shortname: shliujing    ## e.g. wuchong   your duoshuo short name.
disqus_shortname:     ## e.g. wuchong   your disqus short name.  先不放，iamlj

#### Share button
jiathis:
  enable: true ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id: 2063471   ## e.g. 1501277 your jiathis ID. 
  tsina: 5718691796  ## e.g. 1664838973 Your weibo id,It will be used in share button.

#### Analytics
google_analytics:
  enable: true
  id: UA-68500175-1    ## e.g. UA-1766729-8 your google analytics ID.
  site: www.aimlj.com  ## e.g. yangjian.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
baidu_tongji:
  enable: true
  sitecode: 6d42a4beda98d0ebc19c84dc725e1424 ## e.g. e6d1f421bbc9962127a50488f9ed37d1 your baidu tongji site code
cnzz_tongji:
  enable: false
  siteid:    ## e.g. 1253575964 your cnzz tongji site id

#### Miscellaneous
ShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true

#### Custom Search
google_cse: 
  enable: false
  cx:   ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---
baidu_search:     ## http://zn.baidu.com/
  enable: false  ## 暂时停用百度的搜索
  id: 14762287225955482424  ## e.g. "783281470518440642"  for your baidu search id
  site: http://zhannei.baidu.com/cse/search  ## your can change to your site instead of the default site
  
tinysou_search:     ## http://tinysou.com/
  enable: false
  id:  ## e.g. "4ac092ad8d749fdc6293" for your tiny search id
